name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Golang
        uses: actions/setup-go@v2
        with:
          go-version: 1.23

      - name: Run tests
        run: go test -v ./...

      - name: Build
        run: go build -v ./...

      - name: Lint
        run: go fmt ./...
